language: python
sudo: required
cache: pip

python:
  - "2.7"

services:
  - docker

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

stages:
  - linting
  - test

jobs:
  include:
    - stage: linting
      name: "Pre-Commit"
      python: 3.6
      install: pip install pre_commit
      script: pre-commit run --all

env:
  global:
  - VERSION="8.0" TESTS="1" LINT_CHECK="0" INCLUDE="storage_backend,storage_backend_sftp,storage_file,storage_image,storage_thumbnail"

  matrix:
  - TESTS="0" LINT_CHECK="1"
  - ODOO_REPO="OCA/OCB"
  - UNIT_TEST="1" ODOO_REPO="OCA/OCB"
#  - UNIT_TEST="1" ODOO_REPO="odoo/odoo"

before_install:
  - docker run -p 2222:22 -d atmoz/sftp:alpine foo:pass:::upload

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - printf '[options]\n\nrunning_env = dev\nkeychain_key_dev = HRdthrkXp28SCHX0kmwOgIob-82N-w8zWoE_UsctE7E=' > ${HOME}/.openerp_serverrc

script:
  - mv .isort.cfg .isoft.cfg.disabled # to avoid trouble with pylint odoo
  - travis_run_tests

after_success:
  - travis_after_tests_success
